"""统一底层契约包：领域数据（schemas）+ 能力协议（protocol）。

- schemas/   纯数据模型（BaseModel / 结构性标注）：Message、Usage、SessionConn…
- protocol/  能力接口（Protocol）：Messages、Channel、Sessions、ToolTable…

依赖方向唯一：protocol → schemas；两者都不引用具体实现，无成环。
使用方统一从 spec 顶层导入，装配根向具体实现注入。
"""

from .protocol import (
    LLM,
    Channel,
    EventBus,
    Messages,
    Projection,
    ProjectionStore,
    Sessions,
    SessionView,
    ToolTable,
)
from .schemas import (
    AgentEndEvent,
    AgentStartEvent,
    Approval,
    ApprovalRsp,
    AssistantMessage,
    Delta,
    DeltaEnd,
    DiagnosticType,
    Error,
    Inquiry,
    Job,
    JobDispatch,
    JobResult,
    JobStatus,
    Message,
    MessageAdapter,
    MessageDeltaEvent,
    MessageEndEvent,
    MessageStartEvent,
    ModelConfig,
    Notification,
    NotificationUnion,
    Receive,
    ResourceDiagnostic,
    Service,
    ServiceUnion,
    SessionConn,
    SessionEndEvent,
    SessionStartEvent,
    SystemMessage,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolMessage,
    ToolResult,
    ToolStart,
    TurnEndEvent,
    TurnStartEvent,
    Usage,
    UserInput,
    UserMessage,
)

__all__ = [
    # schemas — 领域数据
    "SessionConn",
    "ModelConfig",
    "UserInput",
    "ApprovalRsp",
    "DiagnosticType",
    "ResourceDiagnostic",
    "Message",
    "UserMessage",
    "SystemMessage",
    "ToolMessage",
    "AssistantMessage",
    "MessageAdapter",
    "Usage",
    "Notification",
    "Delta",
    "DeltaEnd",
    "ToolStart",
    "ToolResult",
    "Error",
    "NotificationUnion",
    "Service",
    "Receive",
    "Inquiry",
    "Approval",
    "ServiceUnion",
    "JobDispatch",
    "JobResult",
    "Job",
    "JobStatus",
    # events — 事件总线载荷
    "SessionStartEvent",
    "SessionEndEvent",
    "AgentStartEvent",
    "AgentEndEvent",
    "TurnStartEvent",
    "TurnEndEvent",
    "MessageStartEvent",
    "MessageDeltaEvent",
    "MessageEndEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionEndEvent",
    # protocol — 能力协议
    "Channel",
    "Sessions",
    "Messages",
    "Projection",
    "ProjectionStore",
    "ToolTable",
    "EventBus",
    "LLM",
    "SessionView",
]